version: '3.8'

services:
  device-emulator-standalone:
    image: device-emulator
    container_name: device-emulator-standalone
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      network: host
    command: python src/run_without_scripts.py
    #command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - NGINX_HOST_CONFIG=${NGINX_HOST_CONFIG}
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
        consistency: cached
  device-emulator-production:
    image: device-emulator-production
    build:
      context: .
      dockerfile: Dockerfile

