version: "3.8"

services:
  multithreading:
    image: device-emulator
    container_name: multithreading
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      network: host
    #command: python src/run_without_scripts.py
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
        consistency: cached
  multithreading-production:
    image: multithreading-production
    build:
      context: .
      dockerfile: Dockerfile
